version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_doc:
          filters:
            branches:
              only: master
      - update_changelog:
          filters:
            branches:
              only: master

jobs:
  update_doc:
    working_directory: ~/build
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Update Docs
          working_directory: ~/workdir
          command: |
            cd ~/build
            ls
            ./script.sh
            cd ~/workdir
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git
      - deploy:
          name: Update docs from chaingear repo
          working_directory: ~/workdir/congress
          command: |
            # We need to remove current files in folder to avoid duplicating renamed files
            rm -rf ./site/content/docs/cyberd/*
            cp -r ~/build/docs/. ./site/content/docs/chaingear/
            cp ~/build/CHANGELOG.md ./site/content/docs/chaingear/Changelog.md
            cp ~/build/CONTRIBUTING.md ./site/content/docs/chaingear/Contributing.md
            cp -r ~/build/img/. ./site/content/docs/chaingear/img/.
            git add -N site/content/docs/chaingear
            diff=$(git diff site/content/docs/chaingear/)
            if [[  -n  "$diff" ]]; then
              git config user.email "cybercongress42@gmail.com"
              git config user.name "Cyber Admin"
              git add site/content/docs/chaingear/
              git commit -m "Circle CI: Update Docs"
              # Push quietly to prevent showing the token in log
              git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git master
            fi

  update_changelog:
      working_directory: ~/build
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - setup_remote_docker:
            version: 17.11.0-ce
        - checkout
        - run:
            name: Update Changelog
            command: |
              cid=$(docker run -d -it ferrarimarco/github-changelog-generator:1.14.3 -u cybercongress -p chaingear --exclude-tags-regex .*[.].*[.].*[.].* --token $CHANGELOG_GITHUB_TOKEN )
              docker attach $cid
              docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
              diff=$(git diff CHANGELOG.md)
              if [[  -n  "$diff" ]]; then
                git config --global user.email "cybercongress42@gmail.com"
                git config --global user.name "Cyber Admin"
                git add CHANGELOG.md
                git commit -m "Circle CI: Update Changelog"
                git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/chaingear.git master
              fi
